Blocking all update edges from ocp 4.8 to 4.9
openshift/cincinnati-graph-data pull request #1663
Opened 2022-03-25 20:42 UTC by LalatenduMohanty

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

2022-03-25 20:43 UTC, LalatenduMohanty commented
/hold

2022-03-25 20:48 UTC, wking commented on blocked-edges/4.9.yaml
> +to: 4\.9\..*
[`to` doesn't support regular expressions][1] (only [`from` does][2]), so you'll want to iterate over all 4.9.z and create a copy of this that blocks updates from 4.8.  Amazingly, this is our first to-4.9 block, so we don't need to worry about merging with existing to-4.9 issues.  You can just iterate over all the 4.9.z in `fast-4.9`.

[1]: https://github.com/openshift/cincinnati-graph-data/blame/d8c05513732b51a2a49735497609bcd0c945c1a2/README.md#L102
[2]: https://github.com/openshift/cincinnati-graph-data/blame/d8c05513732b51a2a49735497609bcd0c945c1a2/README.md#L103

2022-03-25 21:32 UTC, wking approved these changes
/lgtm

2022-03-25 22:04 UTC, davidkarlsen commented
Ouch, https://bugzilla.redhat.com/show_bug.cgi?id=2068601 is not public, but we've upgraded from 4.8 to 4.9 - do we risk any etcd problems?

2022-03-28 12:54 UTC, sdodson requested changes

2022-03-28 15:18 UTC, LalatenduMohanty commented on build-suggestions/4.9.yaml
> +  minor_min: 4.8.9999
Fixed

2022-03-28 15:44 UTC, LalatenduMohanty commented
> Ouch, https://bugzilla.redhat.com/show_bug.cgi?id=2068601 is not public, but we've upgraded from 4.8 to 4.9 - do we risk any etcd problems?

We are trying to figure these things out and will make the bug public soon

2022-03-28 17:28 UTC, LalatenduMohanty commented
/test e2e

2022-03-28 17:28 UTC, LalatenduMohanty commented
/test e2e-latest-cincinnati

2022-03-29 15:04 UTC, sdodson commented
/lgtm

2022-03-29 15:18 UTC, merged

2022-03-29 17:29 UTC, wking commented
> https://bugzilla.redhat.com/show_bug.cgi?id=2068601 is not public...

It is now :)