blocked versions due to OCPBUGS-30256
openshift/cincinnati-graph-data pull request #4892
Opened 2024-03-07 00:35 UTC by pepedocs

blocked versions due to OCPBUGS-30256

2024-03-07 02:39 UTC, pepedocs commented
/test e2e-latest-cincinnati

2024-03-07 14:12 UTC, LalatenduMohanty commented
/hold till we link the impact assessment card in the risk. Refer https://github.com/openshift/enhancements/tree/master/enhancements/update/update-blocker-lifecycle for more information.

2024-03-08 18:05 UTC, LalatenduMohanty requested changes
We do not need any conditional risk for a cluster which has already updated to 4.13 , as the risk does not change between 4.13 to 4.14 or 4.14 to 4.15 if the cluster already on that version which has the regression. 
So please remove the risk from 4.14.z, 4.15.z versions

2024-03-08 18:06 UTC, LalatenduMohanty commented
/hold cancel

2024-03-08 18:14 UTC, LalatenduMohanty requested changes

2024-03-08 18:14 UTC, LalatenduMohanty commented on blocked-edges/4.13.0-AROBrokenAcceleratedNetworking.yaml
> +url: https://issues.redhat.com/browse/OCPBUGS-30256
Update this link to https://issues.redhat.com/browse/OPNET-479 in all the files included in this PR

2024-03-08 18:16 UTC, LalatenduMohanty commented
>Disagree. The issue that necessitates the edge occurs when a node reboots, as it would during upgrade. We want to minimize instances of this as SRE has to manually remediate each node.

As per the remediation steps we need to delete .link files to fix the issue. So if a cluster has update to 4.13 and the files are deleted, will these files again get created when they update to 4.14.z?

2024-03-08 23:47 UTC, cblecker commented
/close
in favour of https://github.com/openshift/cincinnati-graph-data/pull/4903

2024-03-08 23:47 UTC, closed without merging