Block 4.7.11 due to bug 1953518
openshift/cincinnati-graph-data pull request #838
Opened 2021-06-04 14:51 UTC by vrutkovs

CMO goes degraded when user monitoring workflow is enabled due to DNS changes https://bugzilla.redhat.com/show_bug.cgi?id=1953518

2021-06-04 15:14 UTC, LalatenduMohanty requested changes

2021-06-04 15:14 UTC, LalatenduMohanty commented on blocked-edges/4.7.11.yaml
> +# CMO goes degraded when user monitoring workflow is enabled due to DNS changes https://bugzilla.redhat.com/show_bug.cgi?id=1953518
4.7.11 has the fix, so this is not correct. We need to block edges to versions before 4.7.11

2021-06-04 15:16 UTC, LalatenduMohanty commented on blocked-edges/4.7.11.yaml
> +# CMO goes degraded when user monitoring workflow is enabled due to DNS changes https://bugzilla.redhat.com/show_bug.cgi?id=1953518
Not all versions before 4.7.11, so trying to find out which version.

2021-06-04 15:20 UTC, LalatenduMohanty commented
/hold As we are not sure if the issue is present in 4.7

2021-06-04 17:06 UTC, sdodson commented
For anyone interested we're searching for instances of this bug affecting 4.7 clusters because while we the same change that fixed the problem in 4.6.31 went into 4.7.11 we have no observed cases of the problem occuring in 4.7.z. Nor do we have root cause for what seemingly introduced the problem in 4.6.30.

2021-06-07 00:24 UTC, sdodson commented
/close
The issue present in 4.6.30 is not present in any 4.7 release because the DNS service change and the CMO change to accommodate that both went into the same release, 4.7.11.

2021-06-07 00:24 UTC, closed without merging